name: Debian 11 package build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the test container image (Debian 11)
      run: docker build . --file .github/Dockerfile.debian11-test --tag amazon-ec2-net-utils-tests:debian11
    - name: Run a containerized scratch build (Debian 11)
      run: docker run -v $(readlink -f $PWD):/src -w /src --entrypoint ".github/container-tests-debian11.sh" amazon-ec2-net-utils-tests:debian11
